Shop.Web/Areas/User/Controllers/WalletController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using RestSharp;
using Shop.Application.Interfaces;
using Shop.Domain.ViewModels.Wallet;
using Shop.Web.Extentions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Web.Areas.User.Controllers
{
    public class WalletController : UserBaseController
    {
        string authority;
        private readonly IWalletService _walletService;
        public WalletController(IWalletService walletService)
        {

            _walletService = walletService;
        }

        #region Charge Wallet
        [HttpGet("Charge-Wallet")]
        public IActionResult ChargeWallet()
        {
            return View();
        }
        [HttpPost("Charge-Wallet"), ValidateAntiForgeryToken]
        public async Task<IActionResult> ChargeWallet(ChargeWalletViewModel charge)
        {
            
            if (ModelState.IsValid)
            {
                var walletId = await _walletService.ChargeWallet(User.GetUserId(), charge, "شارژ حساب");
                var amount = charge.Amount * 10;
                try
                {
                    //RequestParameters Parameters = new RequestParameters("b7531f90-420b-44a3-acf9-3204cc0d7015", amount.ToString(), "شارژ کیف پول", "https://tasland.ir/verify-Payment/" + walletId, "", "");



                    //be dalil in ke metadata be sorate araye ast va do meghdare mobile va email dar metadata gharar mmigirad
                    //shoma mitavanid in maghadir ra az kharidar begirid va set konid dar gheir in sorat khali ersal konid

                    var client = new RestClient(URLs.requestUrl);

                    Method method = Method.Post;

                    var request = new RestRequest("", method);

                    request.AddHeader("accept", "application/json");

                    request.AddHeader("content-type", "application/json");

                    //request.AddJsonBody(Parameters);

                    var requestresponse = client.ExecuteAsync(request);

                    JObject jo = JObject.Parse(requestresponse.Result.Content);

                    string errorscode = jo["errors"].ToString();

                    JObject jodata = JObject.Parse(requestresponse.Result.Content);

                    string dataauth = jodata["data"].ToString();


                    if (dataauth != "[]")
                    {


                        authority = jodata["data"]["authority"].ToString();

                        string gatewayUrl = URLs.gateWayUrl + authority;

                        return Redirect(gatewayUrl);

                    }
                    else
                    {

                        TempData[ErrorMessage] = " عملیات پرداخت با مشکل مواجه شد لطفا مجددا امتحان کنید ";
                        return BadRequest("error " + errorscode);


                    }


                }

                catch (Exception ex)
                {
                    throw new Exception(ex.Message);


                }

            }
            return View(charge);
        }
      
        #endregion

        #region User Wallet
        [HttpGet("user-wallet")]
        public async Task<IActionResult> UserWallet(FilterWalletViewModel filter)
        {
            filter.UserId = User.GetUserId();

            return View(await _walletService.FilterWallet(filter));
        }
        #endregion
        

    }
}

Shop.Web/Areas/User/Views/Shared/Components/UserSideBar/UserSideBar.cshtml
@model User



    <div class="sidebar-profile sidebar-navigation">
        <section class="profile-box">
            <header class="profile-box-header-inline">
                <div class="profile-avatar user-avatar profile-img">
                    <img src="/images/user.png">
                </div>
            </header>
            <footer class="profile-box-content-footer">
                <span class="profile-box-nameuser">@Model.GetUserName() </span>
                <span class="profile-box-registery-date">@Model.CreateDate.ToStringShamsiDate()</span>
                <span class="profile-box-phone">شماره همراه : @Model.PhoneNumber</span>
                <div class="profile-box-tabs">
                    <a asp-controller="Account" asp-action="LogOut" class="profile-box-tab-sign-out"><i class="mdi mdi-logout-variant"></i>خروج از حساب</a>
                </div>
            </footer>
        </section>
        <section class="profile-box">
            <ul class="profile-account-navs">
                <li class="profile-account-nav-item navigation-link-dashboard">
                    <a asp-area="user" asp-controller="home" asp-action="index" class="active">
                        <i class="mdi mdi-account-outline"></i>
                        پروفایل
                    </a>
                </li>
                <li class="profile-account-nav-item navigation-link-dashboard">
                    <a asp-area="user" asp-controller="account" asp-action="EditUserProfile" >
                        <i class="mdi mdi-cart"></i>
                        ویرایش حساب کاربری
                    </a>
                </li>
                <li class="profile-account-nav-item navigation-link-dashboard">
                    <a asp-area="user" asp-controller="account" asp-action="ChangePassword" >
                        <i class="mdi mdi-cart"></i>
                        تغییر رمزعبور
                    </a>
                </li>
                <li class="profile-account-nav-item navigation-link-dashboard">
                    <a asp-area="user" asp-controller="Wallet" asp-action="ChargeWallet" >
                        <i class="mdi mdi-cart"></i>
                        کیف پول شما
                    </a>
                </li>
                <li class="profile-account-nav-item navigation-link-dashboard">
                    <a asp-area="user" asp-controller="Wallet" asp-action="UserWallet" >
                        <i class="mdi mdi-cart"></i>
                        تراکنش ها
                    </a>
                </li>
                <li class="profile-account-nav-item navigation-link-dashboard">
                    <a  asp-area="user" asp-controller="Account" asp-action="FilterUserOrder">
                        <i class="mdi mdi-cart"></i>
                        همه سفارش ها
                    </a>
                </li>
                <li class="profile-account-nav-item navigation-link-dashboard">
                    <a asp-area="user" asp-controller="Account" asp-action="ShowUserFavorites"  >
                        <i class="mdi mdi-heart"></i>
                        لیست علاقه مندی
                    </a>
                </li>
                <li class="profile-account-nav-item navigation-link-dashboard">
                    <a asp-area="user" asp-controller="Account" asp-action="ShowAddress" >
                        <i class="mdi mdi-map-outline"></i>
                        آدرس
                    </a>
                </li>
              
            </ul>
        </section>
    </div>