Shop.Web/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Interfaces;
using Shop.Domain.ViewModels.Admin.Article;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;  
        }
        [HttpGet("ArticleDetail/{articleId}")]
        public async Task<IActionResult> ArticleDetail(long articleId)
        {
            TempData["LatestArticle"] = await _articleService.LatestArticleSingle(articleId);
            return View(await _articleService.AticleDetails(articleId));
        }
     
        public async Task<IActionResult> ArchiveArticle(FilterArticleViewModel filter)
        {
            filter.TakeEntity = 12;
            return View(await _articleService.FilterArticle(filter));
        }
    }
}

Shop.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Shop.Application.Interfaces;
using Shop.Domain.ViewModels.Admin.Product;
using Shop.Domain.ViewModels.Site;
using Shop.Web.Extentions;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Shop.Web.Controllers
{
    public class ProductController : SiteBaseController
    {
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;
        public ProductController(IProductService productService, IOrderService orderService)
        {
            _productService = productService;
            _orderService = orderService;
        }
        public async Task<IActionResult> ArchiveProduct(FilterProductViewModel filter)
        {
            filter.TakeEntity = 12;
            filter.ProductBox = ProductBox.ItemBoxInSite;
            ViewData["ProductGroup"] = await _productService.GetAllProductGroup();
            ViewData["SelectedGroups"] = filter.SelectedGroups;
            return View(await _productService.FilterProduct(filter));
        }
        [HttpGet("ProductDetaeil/{productId}")]
        public async Task<IActionResult> ProductDetail(long productId)
        {
            var detail = await _productService.ProductDetails(productId);
            TempData["RelatedProducts"] = await _productService.RelatedProducts(detail.ProductGroup.UrlName, productId);

            return View(detail);
        }
        [Authorize]
        public async Task<IActionResult> BuyProduct(long productId)
        {
            var orderId = await _orderService.AddOrder(User.GetUserId(), productId);
            return Redirect("/User/Basket/" + orderId);
        }
        [HttpPost]
        public async Task<IActionResult> CreateComment(CreateProductCommentViewModel createComment,IFormCollection form)
        {
            string urlToPost = "https://www.google.com/recaptcha/api/siteverify";
            string secretKey = "6LeLlb8kAAAAAHvKI1wAArU2h3xgXyP53JHZs02C"; // change this
            string gRecaptchaResponse = form["g-recaptcha-response"];

            var postData = "secret=" + secretKey + "&response=" + gRecaptchaResponse;

            // send post data
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(urlToPost);
            request.Method = "POST";
            request.ContentLength = postData.Length;
            request.ContentType = "application/x-www-form-urlencoded";

            using (var streamWriter = new StreamWriter(request.GetRequestStream()))
            {
                streamWriter.Write(postData);
            }

            // receive the response now
            string result = string.Empty;
            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            {
                using (var reader = new StreamReader(response.GetResponseStream()))
                {
                    result = reader.ReadToEnd();
                }
            }

            // validate the response from Google reCaptcha
            var captChaesponse = JsonConvert.DeserializeObject<reCaptchaResponse>(result);
            if (!captChaesponse.Success)
            {
                ViewBag.Message = "Sorry, please validate the reCAPTCHA";
                return View();
            }

            // go ahead and write code to validate username password against database

            if (!String.IsNullOrEmpty(createComment.Comment))
            {
                var res = await _productService.CreateProductComment(createComment, User.GetUserId());
                switch (res)
                {
                    case CreateProductCommentResult.Success:
                        TempData[SuccessMessage] = "نظر شما با موفقیت ثبت شد بعد از باز بینی نمایش داده می شود";
                        return RedirectToAction("ProductDetail", new { productId = createComment.ProductId });
                }
            }
            TempData[ErrorMessage] = "لطفا نظر خودتان را بنویسید";
            return RedirectToAction("ProductDetail", new { productId = createComment.ProductId });
        }
      
    }
}

Shop.Web/Views/Shared/_ArchiveArticleBox.cshtml
@using Shop.Application.Utils;
@model Shop.Domain.Models.Articles.Article

<article class="post-item">
    <div class="post-thumb">
        <a asp-controller="Article" asp-action="ArticleDetail" asp-route-articleId="@Model.Id" class="d-block">
            <img src="/ImageArticle/Thumb/@Model.ImageName" alt="@Model.ArticleTitle" title="@Model.ArticleTitle">
        </a>
    </div>
    <div class="post-content">
        <div class="title">
            <a asp-controller="Article" asp-action="ArticleDetail" asp-route-articleId="@Model.Id">
                <h2 class="title-tag">
                    @Model.ArticleTitle
                </h2>
            </a>
        </div>
        <div class="excerpt">
            @Model.ShortDescription
        </div>
        <span class="post-date">
            <i class="fa fa-calendar"></i>
            @Model.CreateDate.ToStringShamsiDate();
        </span>
    </div>
</article>

Shop.Web/Views/Shared/_ArchiveProductBox.cshtml
@model Shop.Domain.ViewModels.Site.ProductListItemViewModel


<div class="col-lg-3 col-md-3 col-xs-12 order-1 d-block mb-3">
    <section class="product-box product product-type-simple">
        <div class="thumb">
            <a asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@Model.ProductId" class="d-block">
                @if (Model.DicPercent != null)
                {
                    <div class="promotion-badge">فروش ویژه</div>
                }

                @if (Model.DicPercent != null)
                {
                    <div class="discount-d">
                        <span>@Model.DicPercent%<span>تخفیف</span></span>
                    </div>
                }

                <img src="/ImageProduct/Product/@Model.ProductImage" alt="@Model.ProductName" title="@Model.ProductName">
            </a>
        </div>
        <div class="title">
            <a asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@Model.ProductId">
                @Model.ProductName
            </a>
        </div>
        @{
            int prcent = 0;
            if (Model.DicPercent != null)
            {
                prcent = (Model.Price * (int)Model.DicPercent) / 100;

            }
        }

        @if (Model.IsActive)
        {
            @if (Model.DicPercent != null)
            {
                <div class="price">
                    <span class="amount">
                        <del>@Model.Price.ToString("#,0")<span>تومان</span></del>
                        <span>@((Model.Price - prcent).ToString("#,0"))<span>تومان</span></span>
                    </span>
                </div>
            }
            else
            {
                <div class="price">
                    <span class="amount">
                        @Model.Price.ToString("#,0")
                        <span>تومان</span>
                    </span>
                </div>
            }
        }
        else
        {
            <div class="price">
                <span class="amount">
                    @Model.Price.ToString("#,0")
                    <span>تومان</span>
                </span>
            </div>
        }


    </section>
</div>

Shop.Web/Views/Shared/_ArticleBox.cshtml
@model Shop.Domain.ViewModels.Site.ArticlelistItemViewModel
<div class="owl-item active">
    <div class="item">
        <section class="product-box product product-type-simple">
            <div class="thumb">
                <a asp-controller="Article" asp-action="ArticleDetail" asp-route-articleId="@Model.ArticleId" class="d-block">

                    <img src="/ImageArticle/@Model.ArticleImage" alt="@Model.ArticleTitle" title="@Model.ArticleTitle">
                </a>
            </div>
            <h2 class="post-title">
                <a asp-controller="Article" asp-action="ArticleDetail" asp-route-articleId="@Model.ArticleId">
                    @Model.ArticleTitle
                </a>
               
            </h2>
     

        </section>

    </div>
</div>

Shop.Web/Views/Shared/_Custom.cshtml
<script src="~/js/vendor/custom2.js"></script>
<script src="~/js/vendor/jquery.unobtrusive-ajax.min.js"></script>

Shop.Web/Views/Shared/_FooterRefrences.cshtml
<script src="/js/vendor/jquery-3.2.1.min.js"></script>
<script src="/js/vendor/bootstrap.js"></script>
<!-- plugin----------------------------------------------------->
<script src="/js/vendor/owl.carousel.min.js"></script>
<script src="/js/vendor/jquery.countdown.js"></script>
<script src="/js/vendor/jquery.nice-select.min.js"></script>
<script src="/js/vendor/jquery.jqZoom.js"></script>
<!-- main js---------------------------------------------------->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>
<script src='https://www.google.com/recaptcha/api.js'></script>
<script src="/js/main.js"></script>
<script src="/js/vendor/notifications.js"></script>
<script src="/js/vendor/custom.js"></script>
<script src="~/js/vendor/EyePassword.js"></script>

Shop.Web/Views/Shared/_HeaderRefrences.cshtml
<link rel="stylesheet" href="/css/vendor/font-awesome.min.css">
<link rel="stylesheet" href="/css/vendor/materialdesignicons.css">
<!-- plugin-------------------------------------->
<link rel="stylesheet" href="/css/vendor/bootstrap.css">
<link rel="stylesheet" href="/css/vendor/owl.carousel.min.css">
<link rel="stylesheet" href="/css/vendor/nice-select.css">
<link rel="stylesheet" href="/css/vendor/jquery.jqZoom.css">
<!-- main-style---------------------------------->
<link rel="stylesheet" href="/css/main.css">
<link rel="stylesheet" href="/css/responsive.css">
<link href="/css/vendor/notifications.css" rel="stylesheet" />
<link href="~/css/Custom.css" rel="stylesheet" />

Shop.Web/Views/Shared/_LastestArticleBox.cshtml
@model Shop.Domain.ViewModels.Site.ArticlelistItemViewModel

    <div class="item">
        <div class="item-inner">
            <div class="item-thumb">
                <a asp-controller="Article" asp-action="ArticleDetail" asp-route-articleId="@Model.ArticleId" class="img-holder d-block">
                    <img src="/ImageArticle/@Model.ArticleImage" alt="@Model.ArticleTitle" title="@Model.ArticleTitle">
                </a>
            </div>
            <div class="title">
                <a asp-controller="Article" asp-action="ArticleDetail" asp-route-articleId="@Model.ArticleId">
                    <h2 class="title-tag">
                        @Model.ArticleTitle
                    </h2>
                </a>
             
            </div>
        </div>
    </div>

   

Shop.Web/Views/Shared/_LatestProductBox.cshtml
@using Shop.Domain.ViewModels.Site
@model ProductListItemViewModel


<div class="col-lg-4 col-md-6 col-sm-12 col-12 pt-4 pr">
    <div class="card-product-horizontal">
        <div class="card-product-horizontal-img">
            <a asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@Model.ProductId" class="d-block">
                <img src="/ImageProduct/Product/@Model.ProductImage" alt="@Model.ProductName" title="@Model.ProductName">
            </a>
        </div>
        <div class="card-product-horizontal-content">
            <div class="card-product-horizontal-content-title">
                <a asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@Model.ProductId">
                    <h3>@Model.ProductName</h3>
                </a>
            </div>
            @{
                int prcent = 0;
                if (Model.DicPercent != null)
                {
                    prcent = (Model.Price * (int)Model.DicPercent) / 100;

                }
            }
            @if (Model.IsActive)
            {
                @if (Model.DicPercent != null)

                {
                    <div class="card-product-horizontal-content-price">
                        <span class="amount">
                            <del><span>@Model.Price.ToString("#,0")<span>تومان</span></span></del>
                            <span>@((Model.Price - prcent).ToString("#,0"))<span>تومان</span></span>
                        </span>
                    </div>
                }
                else
                {

                    <div class="card-product-horizontal-content-price">
                        <span class="amount">
                           <span>@Model.Price.ToString("#,0")<span>تومان</span></span>   
                        </span>
                    </div>

                }

            }
            else
            {
                <div class="card-product-horizontal-content-price">
                    <span class="amount">
                        اتمام موجودی
                    </span>
                </div>
            }
       
        </div>
    </div>
</div>

Shop.Web/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    @RenderSection("MetaTag", false)
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" type=image/x-icon href=/favicon.ico>
    <!-- font---------------------------------------->
    <partial name="_HeaderRefrences" />
    @RenderSection("styles", false)
    <partial name="_Message" />
</head>

<body>
    <!-- header-------------------------------->
    @await Component.InvokeAsync("SiteHeader")
    <!-- header-------------------------------->
    @RenderBody()
    <!-- footer------------------------------------------->
    @await Component.InvokeAsync("SiteFooter")
    <!-- footer------------------------------------------->
    <!-- scroll_Progress------------------------->
    <div class="progress-wrap">
        <svg class="progress-circle svg-content" id="scrollProgress" viewBox="-1 -1 102 102">
            <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
        </svg>
    </div>
    <!-- scroll_Progress------------------------->

    <partial name="_FooterRefrences">
        @RenderSection("scripts", false)
        <partial name="_Message">

</body>


</html>

Shop.Web/Views/Shared/_Message.cshtml
@if (TempData["SuccessMessage"] != null ||
TempData["WarningMessage"] != null ||
TempData["ErrorMessage"] != null ||
TempData["InfoMessage"] != null)
{
    @if (TempData["SuccessMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowMessage('پیغام موفقیت','@TempData["SuccessMessage"]','success')
            });
        </script>
    }

    @if (TempData["WarningMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowMessage('پیغام اخطار','@TempData["WarningMessage"]','warning')
            });
        </script>
    }

    @if (TempData["ErrorMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowMessage('پیغام خطا','@TempData["ErrorMessage"]','error')
            });
        </script>
    }

    @if (TempData["InfoMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowMessage('پیغام اطالاعیه','@TempData["InfoMessage"]','info')
            });
        </script>
    }
}

Shop.Web/Views/Shared/_Paging.cshtml
@model Shop.Domain.ViewModels.Paging.BasePaging


<div class="pagination-product">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @if (Model.EndPage > Model.PageId)
            {
                <li class="page-item">
                    <a class="page-link" onclick="FillPageId(@(Model.PageId +1))" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }

            @for (int i = Model.StartPage; i <= Model.EndPage; i++)
            {
                <li class="page-item">
                    <a class="page-link @(Model.PageId ==i?"active":"")" onclick="FillPageId(@i)">@i</a>
                </li>
            }

            @if (Model.StartPage < Model.PageId)
            {
                <li class="page-item">
                    <a class="page-link" onclick="FillPageId(@(Model.PageId -1))" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
        </ul>
    </nav>
</div>

Shop.Web/Views/Shared/_ProductBox.cshtml
@model Shop.Domain.ViewModels.Site.ProductListItemViewModel
<div class="owl-item active">
    <div class="item">
        <section class="product-box product product-type-simple">
            <div class="thumb">
                <a asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@Model.ProductId" class="d-block">
                    @if (Model.DicPercent != null)
                    {
                        <div class="promotion-badge">فروش ویژه</div>
                    }
              
                    @if (Model.DicPercent != null)
                    {
                        <div class="discount-d">
                            <span>@Model.DicPercent%</span>
                        </div>
                    }
                    <img src="/ImageProduct/Product/@Model.ProductImage" alt="@Model.ProductName" title="@Model.ProductName">
                </a>
            </div>
            <h2 class="post-title">
                <a asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@Model.ProductId">
                    @Model.ProductName
                </a>
            </h2>
            @{
                int prcent = 0;
                if (Model.DicPercent != null)
                {
                    prcent = (Model.Price * (int)Model.DicPercent) / 100;

                }
            }
            @if (Model.IsActive && Model.Count > 5)
            {


                @if (Model.DicPercent != null)
                {
                    <div class="price">
                        <span class="amount">
                            <del><span>@Model.Price.ToString("#,0")<span>تومان</span></span></del>
                            <ins><span>@((Model.Price-prcent).ToString("#,0"))<span>تومان</span></span></ins>
                        </span>
                    </div>
                }
                else
                {
                    <div class="price">
                        <span class="amount">

                            <ins><span>@Model.Price.ToString("#,0")<span>تومان</span></span></ins>
                        </span>
                    </div>
                }
            }
            else
            {
                <div class="price">
                    <span class="amount">

                        <ins><span>اتمام موجودی</span></ins>
                    </span>
                </div>
            }
        
            <div class="actions">
                <ul>
                    <li class="action-item like">
                        <a asp-area="User" asp-controller="Account" asp-action="UserFavorites" asp-route-productId="@Model.ProductId" class="btn btn-light a">
                            <i class="fa fa-heart-o"></i>
                        </a>
                    </li>
                    @if (Model.IsActive && Model.Count > 5)
                    {

                        <li class="action-item add-to-cart">
                            <a asp-controller="Product" asp-action="BuyProduct" asp-route-productId="@Model.ProductId" class="btn btn-light ">
                                <i class="fa fa-shopping-cart"></i>
                            </a>
                        </li>
                    }
                    </ul>
            </div>
        </section>

    </div>
</div>